defaults:
  - data: single_file
  - _self_

# Cohort directory and name: used for automatically loading configs, saving results, and logging.
cohort_dir: ""
cohort_name: ""

# Path to the task configuration file
config_path: ${cohort_dir}/${cohort_name}.yaml

# Path to store the output file. The `${data._prefix}` addition allows us to add shard specific prefixes in a
# sharded data mode.
output_filepath: ${cohort_dir}/${cohort_name}${data._prefix}.parquet

# Hydra
hydra:
  job:
    name: ${cohort_name}_${now:%Y-%m-%d_%H-%M-%S}
  run:
    dir: ${cohort_dir}/.logs/${hydra.job.name}
  sweep:
    dir: ${cohort_dir}/.logs/${hydra.job.name}
  help:
    app_name: aces-cli
    footer: |-
      Powered by Hydra (https://hydra.cc)
      Use --hydra-help to view Hydra specific help
      ===============================================
    template: |-
      ================== aces-cli ===================
      Welcome to the command-line interface for ACES!

      This end-to-end tool extracts a cohort from the external dataset based on a defined task configuration file
      and saves the output file(s). Several data standards are supported, including 'direct', which requires a
      pre-computed predicates dataframe and a timestamp format, 'esgpt', which requires a dataset in the ESGPT
      format, and 'meds', which requires a dataset in the MEDS format.

      ------------------ Arguments ------------------
      data:
          path (required): path to the data directory if using ESGPT or MEDS, or path to the predicates dataframe (.csv or .parquet) if using 'direct'
          standard (required): data standard, one of 'direct', 'esgpt', or 'meds'
          ts_format (required if data.standard is 'direct'): timestamp format for the data
      cohort_dir (required): cohort directory, used to automatically load configs, saving results, and logging
      cohort_name (required): cohort name, used to automatically load configs, saving results, and logging
      config_path (optional): path to the task configuration file, defaults to '<cohort_dir>/<cohort_name>.yaml'
      output_filepath (optional): path to the output file, defaults to '<cohort_dir>/<cohort_name>.parquet'

      ---------------- Default Config ----------------
      $CONFIG
      ------------------------------------------------

      All fields may be overridden via the command-line interface. For example:

          aces-cli data.path='...' data.standard='...' data.ts_format='...' cohort_dir='...' cohort_name='...'

      ${hydra.help.footer}
