# Leave unchanged to profile on MIMIC-IV-ESD with the readmission risk prediction task as the base task
data_dir: ../MIMIC_ESD_new_schema_08-31-23-1/
configs_dir: configs/
results_dir: results/
experiment_dir: /

# VARIABLES TO BE PROFILED
# Number of rows (randomly sampled, seed=42) from MIMIC-IV-ESD to be used for the base task
num_rows:
  - 10
  - 50
  - 100
  - 500
  - 1000
  - 5000
  - 10000
  - 50000
  - 100000
  - 500000
  - 1000000
  - 5000000
  - 10000000
  - 15000000

# Number of extra predicates on top of the base task
num_predicates: [0, 1, 2, 4, 8, 16]

# Number of extra criteria on top of the base task
num_critera: [0, 1, 2, 4, 8, 16]

# Number of extra windows in series on top of the base task
num_windows_series: [0, 1, 2, 4, 8, 16]

# Number of extra windows in parallel on top of the base task
num_windows_parallel: [0, 1, 2, 4, 8, 16]

# Number of threads to use for the base task
num_threads: [1, 2, 4, 8, 12, 16, 20, 24, 28, 32, 36]
