predicates:
  death:
    code: event_type//DEATH

trigger: _ANY_EVENT

windows:
  target:
    start: trigger
    end: start + 24 hours
    start_inclusive: True
    end_inclusive: True
    label: death
