# Task: Long-term (3 Years) MI Incidence Prediction
predicates:
  admission:
    code: event_type//ADMISSION
  discharge:
    code: event_type//DISCHARGE
  diagnosis_ICD9CM/41071:
    code: diagnosis//ICD9CM/41071
  diagnosis_ICD10CM/I214:
    code: diagnosis//ICD10CM/I214
  # diagnosis_ICD10CM/I21A1:
  #   code: diagnosis//ICD10CM/I21A1
  # diagnosis_ICD9CM/41041:
  #   code: diagnosis//ICD9CM/41041
  # diagnosis_ICD9CM/41011:
  #   code: diagnosis//ICD9CM/41011
  # diagnosis_ICD9CM/41091:
  #   code: diagnosis//ICD9CM/41091
  # diagnosis_ICD10CM/I2119:
  #   code: diagnosis//ICD10CM/I2119
  # diagnosis_ICD9CM/41072:
  #   code: diagnosis//ICD9CM/41072
  # diagnosis_ICD10CM/I2109:
  #   code: diagnosis//ICD10CM/I2109
  # diagnosis_ICD10CM/I213:
  #   code: diagnosis//ICD10CM/I213
  myocardial_infarction:
    expr: or(diagnosis_ICD9CM/41071, diagnosis_ICD10CM/I214)
  # myocardial_infarction:
  #   expr: or(diagnosis_ICD9CM/41071, diagnosis_ICD10CM/I214, diagnosis_ICD10CM/I21A1, diagnosis_ICD9CM/41041, diagnosis_ICD9CM/41011, diagnosis_ICD9CM/41091, diagnosis_ICD10CM/I2119, diagnosis_ICD9CM/41072, diagnosis_ICD10CM/I2109, diagnosis_ICD10CM/I213)

trigger: discharge

windows:
  input:
    start: admission
    end: trigger
    start_inclusive: False
    end_inclusive: True
    index_timestamp: end
  gap:
    start: trigger
    end: start + 365 days
    start_inclusive: False
    end_inclusive: True
    has:
      myocardial_infarction: (None, 0)
  target:
    start: gap.end
    end: start + 1095 days
    start_inclusive: False
    end_inclusive: True
    label: myocardial_infarction
