# Task: Heart Failure Prediction (Cases)
# https://arxiv.org/pdf/1602.03686
predicates:
  age_between_50_and_85:
    code: age//
    value_min: 50
    value_max: 85
    value_min_inclusive: True
    value_max_inclusive: True
  HF_diagnostic_code:
    expr: or(...)
  valid_HF_diagnostic_event:
    expr: and(HF_diagnostic_code, age_between_50_and_85)

trigger: valid_HF_diagnostic_event

windows:
  yr_post_dx:
    start: trigger
    end: start + 1y
    start_inclusive: True
    end_inclusive: False
    has:
      HF_diagnostic_code: (3, None)
  input:
    end: trigger
    start: trigger - 18m
    start_inclusive: True
    end_inclusive: False
    index_timestamp: end
