# https://arxiv.org/pdf/1602.03686
predicates:
  age_between_50_and_85:
    code: age//
    value_min: 50
    value_max: 85
    value_min_inclusive: True
    value_max_inclusive: True

trigger: age_between_50_and_85

windows:
  pre_idx_date:
    start: None
    end: trigger
    has:
      HF_diagnostic_code: (None, 0)
  yr_post_idx_date:
    start: trigger
    end: start + 1y
    start_inclusive: True
    end_inclusive: False
    has:
      HF_diagnostic_code: (None, 1)
  input:
    end: trigger
    start: trigger - 18m
    start_inclusive: True
    end_inclusive: False
