# Task: Abnormal SpO2 Prediction
predicates:
  spo2:
    code: lab_name//O2 saturation pulseoxymetry (%)
  normal_spo2:
    code: lab_name//O2 saturation pulseoxymetry (%)
    value_min: 90
    value_max: 120
    value_min_inclusive: True
    value_max_inclusive: True
  abnormally_low_spo2:
    code: lab_name//O2 saturation pulseoxymetry (%)
    value_max: 90
    value_max_inclusive: False
  abnormally_high_spo2:
    code: lab_name//O2 saturation pulseoxymetry (%)
    value_min: 120
    value_min_inclusive: False
  abnormal_spo2:
    expr: or(abnormally_low_spo2, abnormally_high_spo2)

trigger: normal_spo2

windows:
  input:
    start: NULL
    end: trigger
    start_inclusive: True
    end_inclusive: True
    index_timestamp: end
  gap:
    start: trigger
    end: start + 24h
    start_inclusive: False
    end_inclusive: True
  target:
    start: gap.end
    end: start + 7 days
    start_inclusive: False
    end_inclusive: True
    has:
      spo2: (1, None)
    label: abnormal_spo2
