# Task: Intubation Onset Prediction
# https://www.nature.com/articles/s41598-020-77893-3
predicates:
  icu_admission:
    code:
  icu_discharge:
    code:
  hospital_discharge:
    code:
  death:
    code: event_type//DEATH
  intubation_onset:
    code:
  blood_gas:
    code:
  icu_end_of_stay:
    expr: or(icu_discharge, death, hospital_discharge, _RECORD_END)

trigger: _ANY_EVENT

windows:
  pre_trigger_icu_admit:
    start: trigger
    end: start <- icu_admission
    start_inclusive: True
    end_inclusive: True
    has:
      icu_end_of_stay: (None, 0)
  post_trigger_icu_end_of_stay:
    start: trigger
    end: start -> icu_end_of_stay
    start_inclusive: False
    end_inclusive: True
    has:
      icu_admission: (None, 0)
  input:
    start: None
    end: trigger
    start_inclusive: True
    end_inclusive: True
    index_timestamp: end
  BG_meas:
    start: trigger
    end: start - 24h
    start_inclusive: True
    end_inclusive: True
    has:
      blood_gas: (1, None)
  target:
    start: trigger
    end: start + 24h
    start_inclusive: False
    end_inclusive: True
    label: intubation_onset
