predicates:
  admission:
    column: event_type
    value: ADMISSION
  discharge:
    column: event_type
    value: DISCHARGE
  death:
    column: event_type
    value: DEATH
  covid:
    column: dx
    value: COVID  
  discharge_or_death:
    type: ANY
    predicates: [discharge, death]

windows:
  trigger:
    start: admission
    duration:
    offset:
    end: admission
    excludes:
    includes: 
      - predicate: admission
        min: 1
        max: 1
    st_inclusive: False
    end_inclusive: True
  gap:
    start: trigger.end
    duration: 48 hours
    offset:
    end: gap.start + gap.duration
    excludes: 
      - predicate: admission
      - predicate: discharge
      - predicate: death
    includes: 
    st_inclusive: False
    end_inclusive: True
  target:
    start: gap.end
    duration: 
    offset:
    end: discharge_or_death
    excludes:
    includes: 
      - predicate: discharge_or_death
        min: 1
        max: 1
    st_inclusive: False
    end_inclusive: True
  input:
    start:
    duration: 30 days
    offset: 24 hours
    end: trigger.start + offset
    excludes:  
      - predicate: covid
    includes: 
      - predicate: any
        min: 5
        max:
    st_inclusive: False
    end_inclusive: True
