outlier_detector_config:
  cls: stddev_cutoff
  stddev_cutoff: 1.5
normalizer_config:
  cls: standard_scaler
cohort_name: sample
save_dir: ./sample_data/processed/sample
subject_id_col: MRN
seed: 1
split:
  - 0.8
  - 0.1
do_overwrite: true
DL_chunk_size: null
min_valid_vocab_element_observations: 5
min_valid_column_observations: 5
min_true_float_frequency: 0.1
min_unique_numerical_observations: 20
min_events_per_subject: 3
agg_by_time_scale: 1h
raw_data_dir: ./sample_data/raw/
inputs:
  subjects:
    input_df: ./sample_data/raw//subjects.csv
  admissions:
    input_df: ./sample_data/raw//admit_vitals.csv
    start_ts_col: admit_date
    end_ts_col: disch_date
    ts_format: "%m/%d/%Y, %H:%M:%S"
    event_type:
      - OUTPATIENT_VISIT
      - ADMISSION
      - DISCHARGE
  vitals:
    input_df: ./sample_data/raw//admit_vitals.csv
    ts_col: vitals_date
    ts_format: "%m/%d/%Y, %H:%M:%S"
  labs:
    input_df: ./sample_data/raw//labs.csv
    ts_col: timestamp
    ts_format: "%H:%M:%S-%Y-%m-%d"
measurements:
  static:
    single_label_classification:
      subjects:
        - eye_color
  functional_time_dependent:
    age:
      functor: AgeFunctor
      necessary_static_measurements:
        dob:
          - timestamp
          - "%m/%d/%Y"
      kwargs:
        dob_col: dob
  dynamic:
    multi_label_classification:
      admissions:
        - department
    univariate_regression:
      vitals:
        - HR
        - temp
    multivariate_regression:
      labs:
        - - lab_name
          - lab_value
